import type {
  DoctrineDetailCode,
  DoctrinePackagePin,
  DoctrinePackageRefStatus,
} from "@/lib/oa/doctrine";
import type { ProjectDetailCode } from "@/lib/oa/project";

export type PerceivedCriticality = "LOW" | "STANDARD" | "HIGH";

export interface CreateLocalProjectCommand {
  readonly name: string;
  readonly objective: string;
  readonly context: string;
  readonly perceivedCriticality: PerceivedCriticality;
  readonly constraints: readonly string[];
  readonly shortReference?: string;
  /**
   * Generated by the application caller and reused for retries.
   * It is not an authenticated identity or authority token.
   */
  readonly idempotencyKey: string;
}

export interface LocalProjectDoctrineProjection {
  readonly id: string;
  readonly version: string;
  readonly digest: string;
  readonly status: DoctrinePackageRefStatus;
}

export interface LocalProjectLpsProjection {
  readonly id: string;
  readonly version: 1;
  readonly createdAt: string;
}

export interface LocalProjectCreationView {
  readonly projectId: string;
  readonly projectName: string;
  readonly shortReference?: string;
  readonly objective: string;
  readonly contextSummary: string;
  readonly perceivedCriticality: PerceivedCriticality;
  readonly constraints: readonly string[];
  readonly doctrine: LocalProjectDoctrineProjection;
  readonly lps: LocalProjectLpsProjection;
  readonly localMode: true;
  readonly iam: "NOT_SELECTED";
  readonly productPersistence: "SQLITE_OA_PRODUCT_STORE";
  readonly realAgentExecution: "NOT_AVAILABLE";
  readonly delivery: "NOT_AUTHORIZED";
  readonly cutover: "NOT_AUTHORIZED";
  readonly source: "REAL_LOCAL_CORE";
  readonly fixture: false;
}

export type LocalProjectErrorCode =
  | "INPUT_INVALID"
  | "DOCTRINE_UNRESOLVED"
  | "PROJECT_CREATION_FAILED"
  | "PROJECT_NOT_FOUND"
  | "PROJECTION_INVALID";

export interface LocalProjectError {
  readonly code: LocalProjectErrorCode;
  readonly message: string;
  readonly retryable: boolean;
  readonly field?: keyof CreateLocalProjectCommand;
  readonly doctrineDetailCode?: DoctrineDetailCode;
  readonly projectDetailCode?: ProjectDetailCode;
}

export type LocalAuditStatus =
  | "DISABLED"
  | "RECORDED"
  | "FAILED_NON_BLOCKING";

export type CreateLocalProjectResult =
  | {
      readonly ok: true;
      readonly project: LocalProjectCreationView;
      readonly reusedFromIdempotencyKey: boolean;
      readonly auditStatus: LocalAuditStatus;
    }
  | {
      readonly ok: false;
      readonly error: LocalProjectError;
      readonly auditStatus: LocalAuditStatus;
    };

export type GetLocalProjectOverviewResult =
  | {
      readonly ok: true;
      readonly project: LocalProjectCreationView;
    }
  | {
      readonly ok: false;
      readonly error: LocalProjectError;
    };

export interface LocalVerticalSliceArchitecture {
  readonly accessSurface: "HEADLESS_INTERNAL";
  readonly businessState: "OA_PRODUCT_SQLITE_T_A1";
  readonly doctrine: "T_A0_LOCAL_REGISTRY";
  readonly project: "T_A1_PROJECT_LPS";
  readonly audit: "OPTIONAL_BOUNDED_LOCAL";
  readonly fixtures: "OFF_HAPPY_PATH";
  readonly sessionStorage: "NOT_USED_FOR_BUSINESS_STATE";
  readonly react: false;
  readonly network: false;
  readonly iam: "NOT_SELECTED";
  readonly productPersistence: "SQLITE_OA_PRODUCT_STORE";
  readonly realAgentExecution: "NOT_AVAILABLE";
}

export interface LocalProjectIdSource {
  nextProjectId(): string;
  nextLpsVersionId(): string;
  nextCorrelationId(): string;
}

export interface LocalVerticalSliceCompositionOptions {
  readonly registryRoot: string;
  readonly schemasRoot: string;
  readonly doctrinePackagePin?: DoctrinePackagePin;
  readonly idSource?: LocalProjectIdSource;
  readonly nowIso?: string;
  readonly audit?: import("./audit").LocalProjectCreationAuditPort;
  /**
   * Explicit OA Product SQLite path (tests). Default resolves via
   * SFIA_STUDIO_PRODUCT_DB_PATH / .sfia-exec/product/oa-product.sqlite.
   */
  readonly productDbPath?: string;
}
