/**
 * TEST-ONLY — fake Cursor docs-write external boundary.
 * Writes allowlisted text files into an isolated worktree directory.
 * Same Product StartExecution / Gate D path as REAL; substitutes launch only.
 * ZERO REAL Cursor. ZERO remote Git.
 *
 * CR-GCEC-02: prefer request.docsWriteSpec; constructor options are fallback
 * for unit tests only.
 */
import { createHash } from "node:crypto";
import { mkdir, writeFile, readFile, readdir } from "node:fs/promises";
import path from "node:path";
import {
  M4_BOUNDED_DOCS_WRITE_ACTION,
  M4_REAL_GATEWAY_ADAPTER_ID,
  type RealExecutionLaunchPort,
  type RealLaunchRequest,
  type RealLaunchResult,
  type RealProcessObservation,
} from "@/lib/oa/execution-attempt";

export type FakeDocsWriteLaunchPortOptions = {
  worktreeRoot: string;
  pathAllowlist: readonly string[];
  /** Relative path written on success (must be allowlisted). Fallback only. */
  targetPath?: string;
  failLaunch?: boolean;
  content?: string;
  /** Optional fallback repositoryRef when docsWriteSpec absent. */
  repositoryRef?: string;
};

function normalizeRel(p: string): string {
  const n = p.replace(/\\/g, "/").replace(/^\.\//, "").replace(/\/+$/, "");
  if (!n || n.startsWith("/") || n.split("/").includes("..")) {
    throw new Error("PATH_ESCAPE");
  }
  return n;
}

function isAllowlisted(rel: string, allowlist: readonly string[]): boolean {
  const n = normalizeRel(rel);
  return allowlist.some((a) => {
    const root = normalizeRel(a);
    return n === root || n.startsWith(`${root}/`);
  });
}

export class FakeDocsWriteLaunchPort implements RealExecutionLaunchPort {
  readonly gatewayId = M4_REAL_GATEWAY_ADAPTER_ID;
  readonly externalEffects = true as const;
  readonly calls: RealLaunchRequest[] = [];
  readonly touchedFiles: string[] = [];
  lastDigest: string | null = null;
  lastReport: import("../domain/cursorExecutionReport").CursorExecutionReport | null =
    null;
  private readonly options: FakeDocsWriteLaunchPortOptions;
  private readonly observations = new Map<string, RealProcessObservation>();

  constructor(options: FakeDocsWriteLaunchPortOptions) {
    this.options = options;
  }

  async launch(request: RealLaunchRequest): Promise<RealLaunchResult> {
    this.calls.push(request);
    if (this.options.failLaunch) {
      return {
        outcome: "reject",
        gatewayId: this.gatewayId,
        attemptId: request.attemptId,
        reason: "FAKE_DOCS_WRITE_LAUNCH_FAILED",
        realProcessInvoked: false,
        detailCode: "REAL_LAUNCH_FAILED",
      };
    }
    if (request.action !== M4_BOUNDED_DOCS_WRITE_ACTION) {
      return {
        outcome: "reject",
        gatewayId: this.gatewayId,
        attemptId: request.attemptId,
        reason: "ACTION_NOT_DOCS_WRITE",
        realProcessInvoked: false,
        detailCode: "REAL_AGENT_PROFILE_INVALID",
      };
    }

    const spec = request.docsWriteSpec;
    const pathAllowlist = spec?.pathAllowlist ?? this.options.pathAllowlist;
    const targetPath =
      spec?.targetPath ??
      this.options.targetPath ??
      "docs/functional-design.md";
    const repositoryRef =
      spec?.repositoryRef ?? this.options.repositoryRef ?? "unknown/repo";

    let rel: string;
    try {
      rel = normalizeRel(targetPath);
    } catch {
      return {
        outcome: "reject",
        gatewayId: this.gatewayId,
        attemptId: request.attemptId,
        reason: "PATH_ESCAPE",
        realProcessInvoked: false,
        detailCode: "REAL_WORKSPACE_INVALID",
      };
    }

    if (!isAllowlisted(rel, pathAllowlist)) {
      return {
        outcome: "reject",
        gatewayId: this.gatewayId,
        attemptId: request.attemptId,
        reason: "OUT_OF_SCOPE_WRITE",
        realProcessInvoked: false,
        detailCode: "REAL_WORKSPACE_INVALID",
      };
    }

    const root = path.resolve(this.options.worktreeRoot);
    const abs = path.resolve(root, ...rel.split("/"));
    if (!abs.startsWith(root + path.sep) && abs !== root) {
      return {
        outcome: "reject",
        gatewayId: this.gatewayId,
        attemptId: request.attemptId,
        reason: "PATH_ESCAPE",
        realProcessInvoked: false,
        detailCode: "REAL_WORKSPACE_INVALID",
      };
    }

    await mkdir(path.dirname(abs), { recursive: true });
    const brief = spec?.artifactBrief ?? "Functional design";
    const contentReqs = (spec?.contentRequirements ?? []).join(", ");
    const body =
      this.options.content ??
      `# Functional design\n\nGenerated by FakeDocsWriteLaunchPort\n` +
        `repository=${repositoryRef}\n` +
        `attempt=${request.attemptId}\n` +
        `brief=${brief}\n` +
        `contentRequirements=${contentReqs}\n`;
    await writeFile(abs, body, "utf8");
    this.touchedFiles.push(rel);
    const digest = `sha256:${createHash("sha256").update(body).digest("hex")}`;
    this.lastDigest = digest;

    const report = {
      schemaVersion: "oa.cursor-execution-report.1" as const,
      attemptId: request.attemptId,
      executionContractId: request.executionContractId,
      repositoryRef,
      baseSha: request.baseHeadSha,
      status: "stopped" as const,
      fileEffects: {
        created: [rel],
        modified: [] as string[],
        deleted: [] as string[],
        digests: { [rel]: digest },
      },
      validationEffects: [
        {
          identity: "docs-write-path-allowlist",
          result: "pass" as const,
          summary: "allowlist ok",
        },
      ],
      authorizedEffectsExecuted: [
        "filesystem.create" as const,
        "filesystem.modify" as const,
        "validation.run" as const,
      ],
      stoppedBeforeEffects: [
        "git.commit" as const,
        "git.push" as const,
        "github.pr.create" as const,
        "github.pr.merge" as const,
      ],
    };
    this.lastReport = report;

    const processRef = `proc:fake-docs-write:${request.attemptId}`;
    this.observations.set(processRef, {
      processRef,
      exitCode: 0,
      timedOut: false,
      stdout:
        `FAKE_DOCS_WRITE_OK\nfiles=${rel}\ndigest=${digest}\n` +
        `CURSOR_EXECUTION_REPORT_JSON=${JSON.stringify(report)}\n`,
      stderr: "",
      durationMs: 1,
      realProcessInvoked: true,
      worktreeRef: root,
    });

    return {
      outcome: "ack",
      gatewayId: this.gatewayId,
      attemptId: request.attemptId,
      realProcessInvoked: true,
      processRef,
      worktreeRef: root,
    };
  }

  async observe(processRef: string): Promise<RealProcessObservation | null> {
    return this.observations.get(processRef) ?? null;
  }

  async awaitCompletion(
    processRef: string,
  ): Promise<RealProcessObservation | null> {
    return this.observe(processRef);
  }
}

export async function listRelativeFiles(root: string): Promise<string[]> {
  const out: string[] = [];
  async function walk(dir: string, prefix: string): Promise<void> {
    const entries = await readdir(dir, { withFileTypes: true });
    for (const e of entries) {
      const rel = prefix ? `${prefix}/${e.name}` : e.name;
      if (e.isDirectory()) await walk(path.join(dir, e.name), rel);
      else out.push(rel);
    }
  }
  await walk(root, "");
  return out;
}

export async function sha256File(absPath: string): Promise<string> {
  const buf = await readFile(absPath);
  return `sha256:${createHash("sha256").update(buf).digest("hex")}`;
}
